wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1743221388.017835
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.10.12
      5: 0.16.2
      8:
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: epoch
      6:
      - 3
    - 1: iter
      6:
      - 3
    - 1: train/mini_batch_loss_train
      5: 2
      6:
      - 1
    - 1: train/mini_batch_lr
      5: 2
      6:
      - 1
